Repository lwolf83/Project3---Press-Project, pull requests merged in 2020-03, with the labels that each got.

#13 [+] Created editors and newspapers data set test
  Project 3 - Main/DataCreation.cs
Labels: enhancement

#12 Shops and Adresses test set creation
  Project 3 - Main/DataCreation.cs
  Project 3 - Main/PressContext.cs
Labels: enhancement

#25 Create data set test orders catalogs
  Project 3 - Main/Catalog.cs
  Project 3 - Main/DataCreation.cs
  Project 3 - Main/NewspaperNetworkClass.cd
  Project 3 - Main/Order.cs
  Project 3 - Main/PressContext.cs
  Project 3 - Main/Project 3 - Press Project.csproj
  Project 3 - Main/Shop.cs
  Project 3 - Main/ShopCatalog.cs
Labels: bug

#32 Order catalog bug resolving
  Project 3 - Main/Adress.cs
  Project 3 - Main/CSVDataReader.cs
  Project 3 - Main/Catalog.cs
  Project 3 - Main/City.cs
  Project 3 - Main/ClassDiagram1.cd
  Project 3 - Main/DataCreation.cs
  Project 3 - Main/DatabasePopulator.cs
  Project 3 - Main/Department.cs
  Project 3 - Main/Importer/CSVImporter.cs
  Project 3 - Main/Importer/Mappings/CsvCitiesMapping.cs
  Project 3 - Main/Importer/Mappings/CsvDepartmentMapping.cs
  Project 3 - Main/Importer/Mappings/CsvProvincesMapping.cs
  Project 3 - Main/PressContext.cs
  Project 3 - Main/Program.cs
  Project 3 - Main/Project 3 - Press Project.csproj
  Project 3 - Main/Province.cs
  Project 3 - Main/Shop.cs
  Project 3 - Main/cities.csv
  Project 3 - Main/departments.csv
  Project 3 - Main/regions.csv
Labels: enhancement

#37 Shop lists implemented
  Project 3 - Main/DB/PressContext.cs
  Project 3 - Main/DatabasePopulator.cs
  Project 3 - Main/Program.cs
  Project 3 - Main/ShopCity.cs
  Project 3 - Main/ShopFilter.cs
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
Labels: enhancement

#36 Enhancement authentification
  Project 3 - Main/Authentification.cs
  Project 3 - Main/DatabasePopulator.cs
  Project 3 - Main/IAuthentification.cs
  Project 3 - Main/UserSingleton.cs
  UserInterface/MainWindow.xaml.cs
  UserInterface/UserControlClose.xaml
  UserInterface/UserControlClose.xaml.cs
  UserInterface/UserControlLogin.xaml
  UserInterface/UserControlLogin.xaml.cs
  UserInterface/UserControlLogout.xaml
  UserInterface/UserControlLogout.xaml.cs
  UserInterface/UserControlLogoutClose.xaml.cs
Labels: enhancement

#39 Enhancement lot1 k
  Project 3 - Main/Authentification.cs
  Project 3 - Main/ShopFilter.cs
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
Labels: enhancement

#43 Ag1
  Project 3 - Main/Authentification.cs
  Project 3 - Main/DB/Catalog.cs
  Project 3 - Main/DB/Order.cs
  Project 3 - Main/DB/OrderCatalog.cs
  Project 3 - Main/DatabasePopulator.cs
  Project 3 - Main/OrderCatalogAction.cs
  Project 3 - Main/ShopAdder_DB.cs
  Project 3 - Main/ShopCity.cs
  Project 3 - Main/ShopDetail.cs
  Project 3 - Main/ShopFilter.cs
  Project 3 - Main/UserSingleton.cs
  UserInterface/MainWindow.xaml
  UserInterface/Order/UserControlOrder.xaml
  UserInterface/Order/UserControlOrder.xaml.cs
  UserInterface/UserControlAddShop.xaml.cs
  UserInterface/UserControlDisplayShopDetails.xaml
  UserInterface/UserControlDisplayShopDetails.xaml.cs
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
Labels: good first issue

#42 Location filtration
  Project 3 - Main/DB/Address.cs
  Project 3 - Main/ShopCity.cs
  Project 3 - Main/ShopFilter.cs
  Project 3 - Main/UserSingleton.cs
  Projet 3.sln
  Test/UnitFilterTest.cs
  TestPressProject/TestAuthentification.cs
  TestPressProject/TestPressProject.csproj
  TestPressProject/UnitFilterTest.cs
  UserInterface/MainWindow.xaml.cs
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
Labels: enhancement
