Repository lwolf83/Project3---Press-Project, pull requests merged in 2020-04, with the labels that each got.

#71 Top menu Added, Création of a setter for the main grid
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/UserControlLogin.xaml.cs
  UserInterface/UserControlLogout.xaml.cs
  UserInterface/UserControlSetter.cs
Labels: enhancement

#74 Using Dialog box and extract command part
  Project 3 - Main/Factory/OrderCatalogFactory.cs
  Project 3 - Main/Factory/OrderFactory.cs
  UserInterface/Order/OrderAction.cs
  UserInterface/Order/UserControlOrder.xaml
  UserInterface/Order/UserControlOrder.xaml.cs
Labels: enhancement

#73 Addjournals
  Project 3 - Main/JournalFilter.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlJournal.xaml
  UserInterface/UserControlJournal.xaml.cs
Labels: good first issue

#77 Create newspaper only
  Project 3 - Main/ClassDiagram1.cd
  Project 3 - Main/DB/Editor.cs
  Project 3 - Main/DB/Newspaper.cs
  Project 3 - Main/Importer/CSVImporter.cs
  Project 3 - Main/Partial/Editor.partial.cs
  UserInterface/Tools/DialogBox/DialogBox.xaml.cs
  UserInterface/UserControlAddNewspaper.xaml
  UserInterface/UserControlAddNewspaper.xaml.cs
  UserInterface/UserControlEditor.xaml
  UserInterface/UserControlEditor.xaml.cs
  UserInterface/UserControlJournal.xaml
  UserInterface/UserControlJournal.xaml.cs
Labels: enhancement

#83 Add catalog edition
  Project 3 - Main/DB/Catalog.cs
  Project 3 - Main/Factory/CatalogFactory.cs
  Project 3 - Main/Partial/Catalog.Partial.cs
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlCatalog.xaml
  UserInterface/UserControlCatalog.xaml.cs
Labels: enhancement

#79 Filtering editions
  Project 3 - Main/ClassDiagram1.cd
  Project 3 - Main/DB/Newspaper.cs
  Project 3 - Main/DB/Shop.cs
  Project 3 - Main/NewspaperNetworkClass.cd
  Project 3 - Main/Partial/Catalog.partial.cs
  Project 3 - Main/Partial/Newspaper.partial.cs
  Project 3 - Main/Partial/Shop.partial.cs
  Project 3 - Main/Program.cs
  Project 3 - Main/UserSingleton.cs
  TestPressProject/UnitFilterTest.cs
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/Tools/GraphicalInterface/InputChecker.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlAddNewspaper.xaml
  UserInterface/UserControlAddNewspaper.xaml.cs
  UserInterface/UserControlDisplayShopDetails.xaml.cs
  UserInterface/UserControlEdition.xaml
  UserInterface/UserControlEdition.xaml.cs
  UserInterface/UserControlJournal.xaml
  UserInterface/UserControlJournal.xaml.cs
  UserInterface/UserControlShop.xaml.cs
  UserInterface/UserControlStock.xaml.cs
Labels: enhancement

#82 Add new Editor and Modify Editors
  Project 3 - Main/EditorAddModify.cs
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlAddEditor.xaml
  UserInterface/UserControlAddEditor.xaml.cs
  UserInterface/UserControlModifyEditor.xaml
  UserInterface/UserControlModifyEditor.xaml.cs
Labels: good first issue

#85 Problème de sauvegarde juste après un delete ok, controle des dates ok
  Project 3 - Main/NewspaperGet.cs
  Project 3 - Main/Partial/Catalog.partial.cs
  UserInterface/UserControlCatalog.xaml.cs
Labels: enhancement

#86 Automatic delivery
  Project 3 - Main/ClassDiagram1.cd
  Project 3 - Main/DB/AutomaticOrder.cs
  Project 3 - Main/DB/PressContext.cs
  Project 3 - Main/DatabasePopulator.cs
  Project 3 - Main/Factory/AutomaticOrderFactory.cs
  Project 3 - Main/Factory/OrderCatalogFactory.cs
  Project 3 - Main/Factory/OrderFactory.cs
  Project 3 - Main/Partial/AutomaticOrder.cs
  Project 3 - Main/Program.cs
  TestPressProject/TestAutomaticOrders.cs
  TestPressProject/UnitFilterTest.cs
Labels: enhancement

#88 Iurii2 apr
  Project 3 - Main/Partial/Shop.partial.cs
  UserInterface/MainWindow.xaml
  UserInterface/UserControlModifyNewspaper.xaml
  UserInterface/UserControlModifyNewspaper.xaml.cs
  UserInterface/UserControlStock.xaml
  UserInterface/UserControlStock.xaml.cs
Labels: enhancement

#93 Automatic delivery
  Project 3 - Main/Factory/AutomaticOrderFactory.cs
  Project 3 - Main/Factory/OrderFactory.cs
  Project 3 - Main/NewspaperModifier.cs
  Project 3 - Main/Partial/AutomaticOrder.partial.cs
  Project 3 - Main/Partial/Order.partial.Cs
  Project 3 - Main/Partial/Shop.partial.cs
  Project 3 - Main/ShopAdder_DB.cs
  Project 3 - Main/ShopsLoader.cs
  Project 3 - Main/UserShopsLoader.cs
  Project 3 - Main/UsersLoader.cs
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/ResourceDictionaries/UserControlNewspapersView.xaml
  UserInterface/ResourceDictionaries/UserControlNewspapersView.xaml.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlAutomaticDelivery.xaml
  UserInterface/UserControlAutomaticDelivery.xaml.cs
  UserInterface/UserControlJournal.xaml
  UserInterface/UserControlJournal.xaml.cs
Labels: enhancement

#94 [+] AutomaticOrder + ShopFiltering UnitTests
  Project 3 - Main/Factory/AutomaticOrderFactory.cs
  Project 3 - Main/Partial/AutomaticOrder.partial.cs
  TestPressProject/TestAutomaticOrders.cs
  TestPressProject/TestShopFiltering.cs
Labels: enhancement

#106 Catalog unit test
  TestPressProject/MultiplePropertiesAssertion.cs
  TestPressProject/TestAutomaticOrders.cs
  TestPressProject/TestCatalog.cs
Labels: enhancement

#107 [*] Resolved #99 + 1 other
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
Labels: bug

#108 [*] Resolved #100
  UserInterface/UserControlEdition.xaml
  UserInterface/UserControlEdition.xaml.cs
Labels: bug

#110 Resolved #109 and #97
  Project 3 - Main/Factory/CatalogFactory.cs
  Project 3 - Main/Factory/NewspaperFactory.cs
  Project 3 - Main/Loading/EditorLoader.cs
  Project 3 - Main/Partial/Newspaper.partial.cs
  UserInterface/UserControlAddNewspaper.xaml.cs
Labels: bug

#111 Automatic order
  Project 3 - Main/CatalogLoader.cs
  Project 3 - Main/NewspapersLoader.cs
  Project 3 - Main/Partial/AutomaticOrder.partial.cs
  Project 3 - Main/ShopsLoader.cs
  Project 3 - Main/UserControleAccess.cs
  Project 3 - Main/UserRight.cs
  Project 3 - Main/UserSingleton.cs
  UserInterface/UserControlAutomaticDelivery.xaml
  UserInterface/UserControlAutomaticDelivery.xaml.cs
  UserInterface/UserControlCatalog.xaml.cs
Labels: enhancement

#118 Resolved #48 & #113
  UserInterface/Order/UserControlOrder.xaml.cs
  UserInterface/UserControlShop.xaml
  UserInterface/UserControlShop.xaml.cs
  UserInterface/UserControlStock.xaml
  UserInterface/UserControlStock.xaml.cs
Labels: bug

#120 [+] New main menu
  Project 3 - Main/CatalogLoader.cs
  Project 3 - Main/Initialisator.cs
  Project 3 - Main/Loading/EditorLoader.cs
  Project 3 - Main/Partial/Catalog.partial.cs
  Project 3 - Main/UserSingleton.cs
  UserInterface/MainWindow.xaml
  UserInterface/MainWindow.xaml.cs
  UserInterface/Tools/GraphicalInterface/UserControlSetter.cs
  UserInterface/UserControlEdition.xaml.cs
  UserInterface/UserControlLogin.xaml.cs
  UserInterface/UserControlMainMenu.xaml
  UserInterface/UserControlMainMenu.xaml.cs
Labels: enhancement
